# sh specific configure variables
ac_cv_c_char_unsigned=no
ac_cv_func_setpgrp_void=yes
ac_cv_prog_cc_cross=yes
ac_cv_search_clock_gettime=no
ac_cv_sizeof_char=1
ac_cv_sizeof_double=8
ac_cv_sizeof_float=4
ac_cv_sizeof_int=4
ac_cv_sizeof_long=4
ac_cv_sizeof_long_double=12
ac_cv_sizeof_long_long=8
ac_cv_sizeof_short=2
ac_cv_sizeof_signed_char=1
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=4
ac_cv_sizeof_unsigned_long_long=8
ac_cv_sizeof_unsigned_short=2
ac_cv_sizeof_unsigned_short=2
ac_cv_sizeof_void_p=4
ac_cv_sizeof_off_t=4
# DB2, DB3
db_cv_alignp_t=int
db_cv_fcntl_f_setfd=yes
db_cv_mutex=sh/gcc-assembly
db_cv_spinlocks=sh/gcc
db_cv_sprintf_count=yes
# Python
ac_cv_malloc_zero=yes
ac_cv_opt_olimit_ok=no
ac_cv_olimit_ok=no
